version: '3.8'

services:
  redis:
    image: redis:7-alpine 
    ports:
      - '6379:6379' 
    volumes:
      - redis-data:/data 
    command: redis-server --requirepass redis_password 
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping'] 
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - '8000:8000' 
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8000 
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 

volumes:
  redis-data: 